### ISSUE TITLE
Handle unsuccessful Discord login

### ISSUE THREAD

**Issue by TimJentzsch** [TimJentzsch/valveGamesAnnouncerBot#106]
**Describe the bug**
For unknown reasons, the Discord bot can be caught in a restart loop, leading to the Bot token being revoked by Discord.

**Expected behavior**
Failed restarts should be handled so that the bot only tries to restart a couple of times.

**Comment by zachkont** [comment]
This was a deployment error that has been resolved. What happened was that the watcher was mistakenly watching data files as well, which caused a restart on every healthcheck update.
