### ISSUE TITLE
[FEATURE] Add Steam as "game"

### ISSUE THREAD

**Issue by TimJentzsch** [TimJentzsch/valveGamesAnnouncerBot#15]
**Describe the solution you'd like**
Add Steam as a "game" you can subscribe to.
It should notify you about any Steam-relevant updates, such as new posts on the [Steam Blog](https://steamcommunity.com/games/593110/announcements/), [Steam Client Updates](https://store.steampowered.com/news/?feed=steam_client) and potentially Beta Updates.

**Comment by zachkont** [comment]
Closed by https://github.com/TimJentzsch/valveGamesAnnouncerBot/pull/53
