### ISSUE TITLE
Fix commands in Telegram channels

### ISSUE THREAD

**Issue by TimJentzsch** [TimJentzsch/valveGamesAnnouncerBot#19]
**Describe the bug**
Messages in Telegram channels don't seem to be triggering any message events, so the commands can't be processed.

**To Reproduce**
1. Start the Telegram bot
2. Add the bot as an admin to a channel
3. Write any commands in the channel

The bot will not respond to any commands.

**Expected behavior**
The bot should work just like in groups and DMs.

**Additional context**
This might be a bug in the `node-telegram-bot-api` instead of our code. Similar reports have been made in their issue section ([#167](https://github.com/Telegram-Bot-Node/Nikoro/issues/167), [#489](https://github.com/yagop/node-telegram-bot-api/issues/489)).
Enabling / disabling the group privacy, removing and readding the bot and using different message events didn't work for me.

**Comment by zachkont** [comment]
As mentioned in https://github.com/yagop/node-telegram-bot-api/issues/489 the bot needs to listen to `channel_post` instead of `message` for channel messages. 

Thinking about it again, I don't think I would like random commands appearing in the channel. Ideally, we need a flow that lets people add a channel as a subscriber for the bot provided that the bot has already been added to the channel.

**Comment by TimJentzsch** [comment]
Good find, thanks.

I don't really see a problem with this, as subscribing is a one time event. If we added an option to add a channel remotely via another command, we would need to verify that the person is an admin on that channel, so that would add some complexity as well.

**Comment by zachkont** [comment]
I don't think the extra code is worth it and you may want to subscribe to new games etc, I'd prefer it if I could manage that privately as a bot user. 

Hmm we do need to verify that the person is an admin. Maybe it's too complicated and not worth the effort indeed...

**Comment by TimJentzsch** [comment]
I think fixing this bug, now that we know the source, is very easy, I will attempt to do that. I don't think it hurts if we keep the option to use the bot in channels normally. However, we can definitely think about adding ways to privately manage a bot in a channel.

**Comment by zachkont** [comment]
sounds good
